analysis-paths:
- analyses
clean-targets:
- target
- dbt_packages
config-version: 2
macro-paths:
- macros
model-paths:
- models
models:
  my_new_project:
    example:
      materialized: view
    stage:
      dimension:
         +schema: CYB_STG_SCH
      final:
         +schema: CYB_INTG_SCH   
name: my_new_project
profile: default
seed-paths:
- seeds
snapshot-paths:
- snapshots
target-path: target
test-paths:
- tests
version: 1.0.0
